### ISSUE TITLE
Add "download" functionality and improve design of code blocks with it

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo-theme#11]
<img width="658" alt="screen shot 2017-04-24 at 9 17 54 pm" src="https://cloud.githubusercontent.com/assets/115347/25364912/9ac44ce6-2933-11e7-9ce4-0a7dd37534f2.png">

**Comment by rdwatters** [comment]
One consideration, if I may @budparr, is that I want to make sure to register both the copy and download events for GA...which are currently being tracked on hugodocs.info. If you want more context, please resend me your gmail and I'll give you access to the account.
