### ISSUE TITLE
Improve "Signature" styling and allow for multiple signatures on one page

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo-theme#14]
From issue #13 https://github.com/budparr/gohugo-theme/issues/13#issuecomment-298066907

> Okay, and while looking at the signatures, noticed that when @moorereason added more than one signature, they aren't separated by a line break, for example:

> https://hugodocs-170426.netlify.com/functions/index-function/

<img width="576" alt="hugo___index" src="https://cloud.githubusercontent.com/assets/8184251/25541122/20b6513c-2c13-11e7-9b4b-a39b9b4fcbb1.png">

**Comment by budparr** [comment]
- [ ] Make type size consistent with body copy
- [ ] test for and create separate instances of signatures
- [ ] [consider](https://github.com/budparr/gohugo-theme/issues/13#issuecomment-298066085) putting a heading over the signatures (one heading for all signature instances.

**Comment by moorereason** [comment]
My simple partial for multiple sigs is in https://github.com/rdwatters/hugo-docs-concept/blob/master/themes/hugo-docs-concept/layouts/partials/functions-signature.html

**Comment by budparr** [comment]
Thanks!
