### ISSUE TITLE
Next and prev links point in opposite directions....

### ISSUE THREAD

**Issue by rdwatters** [budparr/gohugo-theme#21]
This could be semi-related to #20 if you already have this in mind, but as a LTR site, I think it makes more sense to have `"<" == "prev"` and `">" == "next"`. I'm guessing you're running into the same quirk that I ran into with my previous theme; i.e., you call `.NextInSection` but it's for the `prev` link. Here's some context:

https://github.com/rdwatters/hugo-docs-concept/blob/master/themes/hugo-docs-concept/layouts/partials/content-footer.html#L23-L44

**Comment by budparr** [comment]
From @digitalcraftsman
> I've a quick question regarding the prev/next buttons in the new theme, e.g. like on [this page](https://hugodocs.info/getting-started/installing/) in the sidebar below the TOC and at the bottom of the page users can go the previous or next page in a section.

> In order to go to the Quickstart in the linked example I have to click the > caret in the sidebar or the right link in the footer. However, the Quickstart guide is ordered before the "Install Hugo" page.
Intuitively I would expect it the other way around. Reading a book might be a good metaphor: if I want to go to the previous page I would move my hand to the left side of the book to do the flip.

possibly related: https://github.com/spf13/hugo/issues/1061

**Comment by budparr** [comment]
I fixed these. It's fairly unintuitive on the code side, so thanks for pointing it out. I'll take a crack at better styling layter. Thanks guys.

**Comment by rdwatters** [comment]
Agreed on the unintuitive part for sure. But with so many sites using it, it strikes me as unreversible. Maybe the solution is for Hugo to someday have `.NextIn "section"` or something similar.
