### ISSUE TITLE
Themes showcase in global navigation should link to themes.gohugo.io

### ISSUE THREAD

**Issue by rdwatters** [budparr/gohugo-theme#29]
This is my fault for not being clearer about (or, embarrassingly, documenting) the front matter fields for content in the docs site. Currently the "Theme Showcase" link in the global navigation links to a more or less blank page. For such pages, I created a `sitelink` field for pages that were to be added to the navigation but link elsewhere. That said, much of this has changed with the new theme, implementing Hugo menus, etc. For reference:

https://github.com/rdwatters/hugo-docs-concept/blob/master/content/themes/theme-showcase.md

**Comment by budparr** [comment]
I'm not following. The global navigation does point to themes.gohugo.io (though, note to self, I don't have it pointing to the https version, though it should be set to force https)

**Comment by rdwatters** [comment]
Oh, sorry...I should have been clearer. I meant this: https://hugodocs.info/themes/theme-showcase/

Now that you mention it, shall I just remove this `.md` from content?

**Comment by budparr** [comment]
Yeah, I think so.

**Comment by rdwatters** [comment]
Done: 

https://github.com/rdwatters/hugo-docs-concept/commit/5612bc414270a7b80674d617d16727033ce40997
