### ISSUE TITLE
Remove the git data from the last updated...

### ISSUE THREAD

**Issue by rdwatters** [budparr/gohugo-theme#8]
This implies that the changes are substantive when they are very often just a typo or two. I think `lastmod` should be the sole data point for this...

See here for some context:

https://github.com/spf13/hugo/issues/2829#issuecomment-289153688

**Comment by budparr** [comment]
Very happy to remove anything. 

Out of this information currently listed, what should I take out?

```
“Introduction to Hugo Templating” was last updated: April 7, 2017

Commit: fixing typo for code block on templates introduction (4ae5739) 
Release: Hugo v0.20 documentation

```

**Comment by rdwatters** [comment]
> Commit: fixing typo for code block on templates introduction (4ae5739) 
Release: Hugo v0.20 documentation

I think the last updated is great. Thanks @budparr !
