### ISSUE TITLE
Consider fixed navigation?

### ISSUE THREAD

**Issue by rdwatters** [budparr/gohugo-theme#9]
I'm open to conversation on this, but what are your thoughts on keeping the site nav and TOC fixed items? Some pages are very long, and the TOC at the head of the page does little to make the content more navigable:

http://hugodocs-170421.surge.sh/templates/lists/

Further, do you have any thoughts on smooth scrolling so that it doesn't look like the user went to a separate page on mobile?

**Comment by budparr** [comment]
I will likely add smooth scrolling back in. As I mentioned on Gitter, I start by taking everything out, then adding back in in order of the most essential scripts until I hit my budget (trying to keep speed index close to 1000).  I think right now I just have docsearch, clipboardjs, and hljs (which I haven't gotten to work yet). 

re: fixed menu. I tend to agree. To be perfectly honest, I'm having a technical difficulty with it. I'm using flexbox to control those three columns and the `fixed` bonks the third column in many circumstances. So I intend to revisit it.

**Comment by rdwatters** [comment]
> To be perfectly honest, I'm having a technical difficulty with it

Can I help?

**Comment by budparr** [comment]
You have everything at your disposal to work on it and do a P.R. so you're welcome to if you have an idea. That said, I'm working on revamping quite a few things at the moment, so you may want to save yourself the time. That said that said :) if you see something glaring that I'm just missing, you're welcome to throw it out there here in the issue.

**Comment by rdwatters** [comment]
> I'm working on revamping quite a few things at the moment, so you may want to save yourself the time

I figured as much. Once you're at the point where you're slowing down, let me know and I'm happy to submit a PR. I know some of the JS on the current gohugo.io gets a bit laborious, so please keep me apprised of how I can help :smile:

**Comment by budparr** [comment]
I added these, in a quick and dirty way. Still need to do some testing, etc. but going to close this for now.

**Comment by rdwatters** [comment]
Ah, I like the quick and dirty fix, actually. Looks great on desktop. As a next step (future iteration), what do you think about making this a fixed nav/off-canvas piece on mobile? That's the form factor in which the extra long pages strike me as especially difficult to traverse. Thanks @budparr

**Comment by budparr** [comment]
> what do you think about making this a fixed nav/off-canvas piece on mobile?
Not sure I understand the benefit. I think long-pages are hard to understand no matter where you put the menu, and better to chunk the content into smaller pieces.

Right now, my speed index on repeat views is 812 (1012 with no cache), which is about right, so any additional scripts (and I'm not–so far–using any jquery) will need to be, in my view, absolutely critical. Speed is the ultimate feature.

**Comment by rdwatters** [comment]
Works for me; by the way, I like the smooth scroll you implemented. Is that a Bud Parr original? More importantly, may I steal it? :smile:

**Comment by budparr** [comment]
Good. Sorry that I'm so conservative.
And, I've only lightly touched the smoothscroll. I think you'll like working with Webpack, by the way. Once it's set up, it's super easy to add new scripts. Much easer, IMHO, than Gulp.

**Comment by rdwatters** [comment]
> Much easer, IMHO, than Gulp.

Something I'm discovering for sure. You got me interested and I'm taking a course on Laracasts. It will take some getting used to, but I think we share similar thoughts on, for example, components....and certain tendencies for SCSS to get totally unreadable.
